name: GitHub Actions
run-name: Basic CI/CD
on:
  - push
jobs:
  Job-1:
    runs-on: ubuntu-latest
    steps:
      - run:
          echo "🎉 The job was automatically triggered by a ${{ github.event_name }}
          event."
      - run: echo "🎉 The job was triggered by a ${{ github.actor }} user."
  Job-2:
    runs-on: ubuntu-latest
    steps:
      - run:
          echo "🎉 The job was automatically triggered by a ${{ github.event_name }}
          event."
  Job-3:
    runs-on: ubuntu-latest
    needs: [Job-1, Job-2]
    steps:
      - run: npm install -g axios
      - run: axios -v
