name: Retrieve Secrets
on:
  workflow_dispatch
jobs:
    Retrieve-Secrets:
        runs-on: ubuntu-latest
        steps:
            - name: "Retrieve Secrets"
              env:
                  super_secret: ${{ secrets.TEST_SECRET }}
              run: |
                  echo "${{ secrets.TEST_SECRET }}"