name: Secrects
on:
  push:
jobs:
    Retrieve-Secrets:
        runs-on: ubuntu-latest
        steps:
            - name: "Retrieve Secrets"
              env:
                  SECRET_NAME: ${{ secrets.TEST_SECRET }}
              run: |
                echo "🎉 Secret retrieved successfully, $SECRET_NAME"