name: Secrects
on:
  push:
jobs:
    Retrieve-Secrets:
        runs-on: ubuntu-latest
        steps:
            - name: "Retrieve Secrets"
              env:
                  super_secret: ${{ secrets.TEST_SECRET }}
              run: |
                example-command "$super_secret"